-- PLANETS
INSERT INTO public.planets (name, days_to_rotation, days_to_orbit, diameter_km, climate, standard_gravity, terrain, surface_water, population) VALUES
    ('Abafar',0,0,0,'UNKNOWN',0,'',0,0),
    ('Abregado-rae',0,0,0,'UNKNOWN',0,'',0,0),
    ('Agamar',0,0,0,'UNKNOWN',0,'',0,0),
    ('Ahch-To',0,0,0,'UNKNOWN',0,'',0,0),
    ('Ajan Kloss',0,0,0,'UNKNOWN',0,'',0,0),
    ('Akiva',0,0,0,'UNKNOWN',0,'',0,0),
    ('Alderaan',24,364,12500,'TEMPERATE',1,'grasslands, mountains',40,2000000000),
    ('Aleen',0,0,0,'UNKNOWN',0,'',0,0),
    ('Aleen Minor',0,0,0,'UNKNOWN',0,'',0,0),
    ('Alzoc III',0,0,0,'UNKNOWN',0,'',0,0),
    ('Ambria',0,0,0,'UNKNOWN',0,'',0,0),
    ('Anaxes',0,0,0,'UNKNOWN',0,'',0,0),
    ('Ando',0,0,0,'UNKNOWN',0,'',0,0),
    ('Anoat',0,0,0,'UNKNOWN',0,'',0,0),
    ('Anoth',0,0,0,'UNKNOWN',0,'',0,0),
    ('Arkania',0,0,0,'UNKNOWN',0,'',0,0),
    ('Atollon',0,0,0,'UNKNOWN',0,'',0,0),
    ('Bakura',0,0,0,'UNKNOWN',0,'',0,0),
    ('Balnab',0,0,0,'UNKNOWN',0,'',0,0),
    ('Batuu',0,0,0,'UNKNOWN',0,'',0,0),
    ('Bespin',12,5110,118000,'TEMPERATE',1.5,'gas giant',0,6000000),
    ('Bestine IV',26,680,6400,'TEMPERATE',0,'rocky islands, oceans',98,62000000),
    ('Bonadan',0,0,0,'UNKNOWN',0,'',0,0),
    ('Borleias',0,0,0,'UNKNOWN',0,'',0,0),
    ('Bracca',0,0,0,'UNKNOWN',0,'',0,0),
    ('Byss',0,0,0,'UNKNOWN',0,'',0,0),
    ('Cantonica',0,0,0,'UNKNOWN',0,'',0,0),
    ('Carida',0,0,0,'UNKNOWN',0,'',0,0),
    ('Castilon',0,0,0,'UNKNOWN',0,'',0,0),
    ('Cato Neimoidia',25,278,0,'TEMPERATE',1,'mountains, fields, forests, rock arches',0,10000000),
    ('Cerea',27,386,0,'TEMPERATE',1,'verdant',20,450000000),
    ('Champala',27,318,0,'TEMPERATE',1,'oceans, rainforests, plateaus',0,3500000000),
    ('Chandrila',20,368,13500,'TEMPERATE',1,'plains, forests',40,1200000000),
    ('Christophsis',0,0,0,'UNKNOWN',0,'',0,0),
    ('Concord Dawn',0,0,0,'UNKNOWN',0,'jungles, forests, deserts',0,0),
    ('Corellia',25,329,11000,'TEMPERATE',1,'plains, urban, hills, forests',70,3000000000),
    ('Coruscant',24,368,12240,'TEMPERATE',1,'cityscape, mountains',0,1000000000000),
    ('Crait',0,0,0,'UNKNOWN',0,'',0,0),
    ('Da Soocha V',0,0,0,'UNKNOWN',0,'',0,0),
    ('Dagobah',23,341,8900,'TROPICAL',0.9,'swamp, jungles',8,0),
    ('Dantooine',25,378,9830,'TEMPERATE',1,'oceans, savans, mountains, grasslands',0,1000),
    ('Dathomir',24,491,10480,'TEMPERATE',0.9,'forests, deserts, savans',0,5200),
    ('Devaron',0,0,0,'UNKNOWN',0,'',0,0),
    ('Dorin',22,409,13400,'TEMPERATE',1,'',0,0),
    ('D''Qar',0,0,0,'UNKNOWN',0,'',0,0),
    ('Drall',0,0,0,'UNKNOWN',0,'',0,0),
    ('Dromund Kaas',0,0,0,'UNKNOWN',0,'',0,0),
    ('Dxun',0,0,0,'UNKNOWN',0,'',0,0),
    ('Eadu',0,0,0,'UNKNOWN',0,'',0,0),
    ('Endor',18,402,4900,'TEMPERATE',0.85,'forests, mountains, lakes',8,30000000),
    ('Er''kit',0,0,0,'UNKNOWN',0,'',0,0),
    ('Eriadu',24,360,13490,'HOT',1,'cityscape',0,22000000000),
    ('Esseles',0,0,0,'UNKNOWN',0,'',0,0),
    ('Exegol',0,0,0,'UNKNOWN',0,'',0,0),
    ('Felucia',34,231,9100,'TROPICAL',0.75,'fungus forests',0,8500000),
    ('Florrum',0,0,0,'UNKNOWN',0,'',0,0),
    ('Fondor',0,0,0,'UNKNOWN',0,'',0,0),
    ('Geonosis',30,256,11370,'ARID',0.9,'rock, desert, mountain, barren',5,100000000000),
    ('Glee Anselm',33,206,15600,'TEMPERATE',1,'lakes, islands, swamps, seas',80,500000000),
    ('Hapes',0,0,0,'UNKNOWN',0,'',0,0),
    ('Haruun Kal',25,383,10120,'TEMPERATE',0.98,'toxic cloudsea, plateaus, volcanoes',0,705300),
    ('Honoghr',0,0,0,'UNKNOWN',0,'',0,0),
    ('Hosnian Prime',0,0,0,'UNKNOWN',0,'',0,0),
    ('Hoth',23,549,7200,'ARCTIC',1.1,'tundra, ice caves, mountain ranges',100,0),
    ('Iego',0,0,0,'UNKNOWN',0,'',0,0),
    ('Iktotch',22,481,0,'ARID',1,'rocky',0,0),
    ('Ilum',0,0,0,'UNKNOWN',0,'',0,0),
    ('Iridonia',29,413,0,'UNKNOWN',0,'rocky canyons, acid pools',0,0),
    ('Ithor',0,0,0,'UNKNOWN',0,'',0,0),
    ('Jakku',0,0,0,'UNKNOWN',0,'deserts',0,0),
    ('Jedha',0,0,0,'UNKNOWN',0,'',0,0),
    ('Jestefad',0,0,0,'UNKNOWN',0,'',0,0),
    ('J''t''p''tan',0,0,0,'UNKNOWN',0,'',0,0),
    ('Kalee',23,378,13850,'TEMPERATE',1,'rainforests, cliffs, canyons, seas',0,4000000000),
    ('Kamino',27,463,19720,'TEMPERATE',1,'ocean',100,1000000000),
    ('Kashyyyk',26,381,12765,'TROPICAL',1,'jungle, forests, lakes, rivers',60,45000000),
    ('Kef Bir',0,0,0,'UNKNOWN',0,'',0,0),
    ('Kessel',0,0,0,'UNKNOWN',0,'',0,0),
    ('Khomm',0,0,0,'UNKNOWN',0,'',0,0),
    ('Kijimi',0,0,0,'UNKNOWN',0,'',0,0),
    ('Korriban',0,0,0,'UNKNOWN',0,'',0,0),
    ('Kothlis',0,0,0,'UNKNOWN',0,'',0,0),
    ('Kuat',0,0,0,'UNKNOWN',0,'',0,0),
    ('Lah''mu',0,0,0,'UNKNOWN',0,'',0,0),
    ('Lothal',0,0,0,'UNKNOWN',0,'',0,0),
    ('Lotho Minor',0,0,0,'UNKNOWN',0,'',0,0),
    ('Lwhekk',0,0,0,'UNKNOWN',0,'',0,0),
    ('Malachor',0,0,0,'UNKNOWN',0,'',0,0),
    ('Malastare',26,201,18880,'TEMPERATE',1.56,'swamps, deserts, jungles, mountains',0,2000000000),
    ('Mandalore',0,0,0,'UNKNOWN',0,'',0,0),
    ('Maridun',0,0,0,'UNKNOWN',0,'',0,0),
    ('Mimban',0,0,0,'UNKNOWN',0,'',0,0),
    ('Mirial',0,0,0,'UNKNOWN',0,'deserts',0,0),
    ('Mon Cala',21,398,11030,'TEMPERATE',1,'oceans, reefs, islands',100,27000000000),
    ('Moraband',0,0,0,'UNKNOWN',0,'',0,0),
    ('Mortis',0,0,0,'UNKNOWN',0,'',0,0),
    ('Mustafar',36,412,4200,'HOT',1,'volcanoes, lava rivers, mountains, caves',0,20000),
    ('Muunilinst',28,412,13800,'TEMPERATE',1,'plains, forests, hills, mountains',25,5000000000),
    ('Mygeeto',12,167,10088,'ARCTIC',1,'glaciers, mountains, ice canyons',0,19000000),
    ('Myrkr',0,0,0,'UNKNOWN',0,'',0,0),
    ('Naboo',26,312,12120,'TEMPERATE',1,'grassy hills, swamps, forests, mountains',12,4500000000),
    ('Nal Hutta',87,413,12150,'TEMPERATE',1,'urban, oceans, swamps, bogs',0,7000000000),
    ('Nevarro',0,0,0,'UNKNOWN',0,'',0,0),
    ('Nkllon',0,0,0,'UNKNOWN',0,'',0,0),
    ('Numidian Prime',0,0,0,'UNKNOWN',0,'',0,0),
    ('N''zoth',0,0,0,'UNKNOWN',0,'',0,0),
    ('Ojom',0,0,0,'SUBARCTIC',0,'oceans, glaciers',100,500000000),
    ('Onderon',0,0,0,'UNKNOWN',0,'',0,0),
    ('Ord Mantell',26,334,14050,'TEMPERATE',1,'plains, seas, mesas',10,4000000000),
    ('Pasaana',0,0,0,'UNKNOWN',0,'',0,0),
    ('Pillio',0,0,0,'UNKNOWN',0,'',0,0),
    ('Polis Massa',24,590,0,'TEMPERATE',0.56,'airless asteroid',0,1000000),
    ('Quermia',0,0,0,'UNKNOWN',0,'',0,0),
    ('Ralltiir',0,0,0,'UNKNOWN',0,'',0,0),
    ('Rattatak',0,0,0,'UNKNOWN',0,'',0,0),
    ('Rishi',0,0,0,'UNKNOWN',0,'',0,0),
    ('Rodia',29,305,7549,'HOT',1,'jungles, oceans, urban, swamps',60,1300000000),
    ('Rugosa',0,0,0,'UNKNOWN',0,'',0,0),
    ('Ruusan',0,0,0,'UNKNOWN',0,'',0,0),
    ('Ryloth',30,305,10600,'TEMPERATE',1,'mountains, valleys, deserts, tundra',5,1500000000),
    ('Sacorria',0,0,0,'UNKNOWN',0,'',0,0),
    ('Saleucami',26,392,14920,'HOT',0,'caves, desert, mountains, volcanoes',0,1400000000),
    ('Savareen',0,0,0,'UNKNOWN',0,'',0,0),
    ('Scarif',0,0,0,'UNKNOWN',0,'',0,0),
    ('Selonia',0,0,0,'UNKNOWN',0,'',0,0),
    ('Serenno',0,0,0,'UNKNOWN',0,'rainforests, rivers, mountains',0,0),
    ('Shili',0,0,0,'TEMPERATE',1,'cities, savanhs, seas, plains',0,0),
    ('Sissubo',0,0,0,'UNKNOWN',0,'',0,0),
    ('Skako',27,384,0,'TEMPERATE',1,'urban, vines',0,500000000000),
    ('Socorro',20,326,0,'ARID',1,'deserts, mountains',0,300000000),
    ('Sorgan',0,0,0,'UNKNOWN',0,'',0,0),
    ('Starkiller Base',0,0,0,'UNKNOWN',0,'',0,0),
    ('Stewjon',0,0,0,'TEMPERATE',1,'grass',0,0),
    ('Subterrel',0,0,0,'UNKNOWN',0,'',0,0),
    ('Sullust',20,263,12780,'HOT',1,'mountains, volcanoes, rocky deserts',5,18500000000),
    ('Takodana',0,0,0,'UNKNOWN',0,'',0,0),
    ('Tatooine',23,304,10465,'ARID',1,'desert',1,200000),
    ('Teth',0,0,0,'UNKNOWN',0,'',0,0),
    ('Tholoth',0,0,0,'UNKNOWN',0,'',0,0),
    ('Thyferra',0,0,0,'UNKNOWN',0,'',0,0),
    ('Toprawa',0,0,0,'UNKNOWN',0,'',0,0),
    ('Toydaria',21,184,7900,'TEMPERATE',1,'swamps, lakes',0,11000000),
    ('Trandosha',25,371,0,'ARID',0.62,'mountains, seas, grasslands, deserts',0,42000000),
    ('Troiken',0,0,0,'UNKNOWN',0,'desert, tundra, rainforests, mountains',0,0),
    ('Tund',48,1770,12190,'UNKNOWN',0,'barren, ash',0,0),
    ('Umbara',0,0,0,'UNKNOWN',0,'',0,0),
    ('Utapau',27,351,12900,'TEMPERATE',1,'scrublands, savan, canyons, sinkholes',0.9,95000000),
    ('Vandor-I',0,0,0,'UNKNOWN',0,'',0,0),
    ('Vardos',0,0,0,'UNKNOWN',0,'',0,0),
    ('Vortex',0,0,0,'UNKNOWN',0,'',0,0),
    ('Vulpter',22,391,14900,'TEMPERATE',1,'urban, barren',0,421000000),
    ('Wayland',0,0,0,'UNKNOWN',0,'',0,0),
    ('Wobani',0,0,0,'UNKNOWN',0,'',0,0),
    ('Wrea',0,0,0,'UNKNOWN',0,'',0,0),
    ('Yavin Prime',0,0,0,'UNKNOWN',0,'',0,0),
    ('Yavin IV',24,4818,10200,'TROPICAL',1,'jungle, rainforests',8,1000),
    ('Zeffo',0,0,0,'UNKNOWN',0,'',0,0),
    ('Zolan',0,0,0,'UNKNOWN',0,'',0,0),
    ('Zonama Sekot',0,0,0,'UNKNOWN',0,'',0,0),
    ('Zygerria',0,0,0,'UNKNOWN',0,'',0,0),
    ('Unknown',0,0,0,'UNKNOWN',0,'',0,0);


-- SPECIES
INSERT INTO public.species (name, species_type, average_height, average_lifespan, language, homeworld) VALUES
    ('Aleena','REPTILE',80,79,'Aleena', public.planet_name_to_id('Aleen Minor')),
    ('Besalisk','AMPHIBIAN',178,75,'besalisk', public.planet_name_to_id('Ojom')),
    ('Cerean','MAMMAL',200,0,'Cerean', public.planet_name_to_id('Cerea')),
    ('Chagrian','AMPHIBIAN',190,0,'Chagria', public.planet_name_to_id('Champala')),
    ('Clawdite','REPTILIAN',180,70,'Clawdite', public.planet_name_to_id('Zolan')),
    ('Droid','ARTIFICIAL',0,1000,'NA', public.planet_name_to_id('Unknown')),
    ('Dug','MAMMAL',100,0,'Dugese', public.planet_name_to_id('Malastare')),
    ('Ewok','MAMMAL',100,0,'Ewokese', public.planet_name_to_id('Endor')),
    ('Geonosian','INSECTOID',178,0,'Geonosian', public.planet_name_to_id('Geonosis')),
    ('Gungan','AMPHIBIAN',190,0,'Gungan basic', public.planet_name_to_id('Naboo')),
    ('Human','MAMMAL',180,120,'Galactic Basic', public.planet_name_to_id('Coruscant')),
    ('Hutt','GASTROPOD',300,1000,'Huttese', public.planet_name_to_id('Nal Hutta')),
    ('Iktotchi','MAMMAL',180,0,'Iktotchese', public.planet_name_to_id('Iktotch')),
    ('Kaleesh','REPTILE',170,80,'Kaleesh', public.planet_name_to_id('Kalee')),
    ('Kaminoan','AMPHIBIAN',220,80,'Kaminoan', public.planet_name_to_id('Kamino')),
    ('Kel Dor','MAMMAL',180,70,'Kel Dor', public.planet_name_to_id('Dorin')),
    ('Mirialan','MAMMAL',180,0,'Mirialan', public.planet_name_to_id('Mirial')),
    ('Mon Calamari','AMPHIBIAN',160,0,'Mon Calamarian', public.planet_name_to_id('Mon Cala')),
    ('Muun','MAMMAL',190,100,'Muun', public.planet_name_to_id('Muunilinst')),
    ('Nautolan','AMPHIBIAN',180,70,'Nautila', public.planet_name_to_id('Glee Anselm')),
    ('Neimoidian','MAMMAL',180,0,'Neimoidia', public.planet_name_to_id('Cato Neimoidia')),
    ('Pau''an','MAMMAL',190,700,'Utapese', public.planet_name_to_id('Utapau')),
    ('Quermian','MAMMAL',240,86,'Quermian', public.planet_name_to_id('Quermia')),
    ('Rodian','REPTILE',170,0,'Galactic Basic', public.planet_name_to_id('Rodia')),
    ('Skakoan','MAMMAL',0,0,'Skakoan', public.planet_name_to_id('Skako')),
    ('Sullustan','MAMMAL',180,0,'Sullutese', public.planet_name_to_id('Sullust')),
    ('Tholothian','MAMMAL',0,0,'Tholothian', public.planet_name_to_id('Tholoth')),
    ('Togruta','MAMMAL',180,94,'Togruti', public.planet_name_to_id('Shili')),
    ('Toong','INSECTOID',200,0,'Tundan', public.planet_name_to_id('Tund')),
    ('Toydarian','MAMMAL',120,91,'Toydarian', public.planet_name_to_id('Toydaria')),
    ('Trandoshan','REPTILE',200,0,'Dosh', public.planet_name_to_id('Trandosha')),
    ('Twi''lek','MAMMALS',200,0,'Twi''leki', public.planet_name_to_id('Ryloth')),
    ('Vulptereen','MAMMALS',100,0,'vulpterish', public.planet_name_to_id('Vulpter')),
    ('Wookiee','MAMMAL',210,400,'Shyriiwook', public.planet_name_to_id('Kashyyyk')),
    ('Xexto','MAMMAL',125,0,'Xextese', public.planet_name_to_id('Troiken')),
    ('Yoda''s species','MAMMAL',66,900,'Galactic basic', public.planet_name_to_id('Unknown')),
    ('Zabrak','MAMMAL',180,0,'Zabraki', public.planet_name_to_id('Iridonia'));


-- CHARACTERS
INSERT INTO public.characters (name, height, mass, hair_color, skin_color, eye_color, birth_year, gender, homeworld, species, main_affiliation) VALUES
    ('Luke Skywalker',172,77,'BLOND','FAIR','BLUE',-19,'MALE', public.planet_name_to_id('Tatooine'), public.species_name_to_id('Human'),'REBEL_ALLIANCE'),
    ('C-3PO',167,75,'NONE','GOLD','YELLOW',-112,'NA', public.planet_name_to_id('Tatooine'), public.species_name_to_id('Droid'),'REBEL_ALLIANCE'),
    ('R2-D2',96,32,'NONE','WHITE','RED',-33,'NA', public.planet_name_to_id('Naboo'), public.species_name_to_id('Droid'),'REBEL_ALLIANCE'),
    ('Darth Vader',202,136,'NONE','WHITE','YELLOW',-41.9,'MALE', public.planet_name_to_id('Tatooine'), public.species_name_to_id('Human'),'GALACTIC_EMPIRE'),
    ('Leia Organa',150,49,'BROWN','LIGHT','BROWN',-19,'FEMALE', public.planet_name_to_id('Alderaan'), public.species_name_to_id('Human'),'REBEL_ALLIANCE'),
    ('Owen Lars',178,120,'BROWN','LIGHT','BLUE',-52,'MALE', public.planet_name_to_id('Tatooine'), public.species_name_to_id('Human'),'UNAFFILIATED'),
    ('Beru Whitesun Lars',165,75,'BROWN','LIGHT','BLUE',-47,'FEMALE', public.planet_name_to_id('Tatooine'), public.species_name_to_id('Human'),'UNAFFILIATED'),
    ('R5-D4',97,32,'NONE','WHITE','RED',0,'NA', public.planet_name_to_id('Tatooine'), public.species_name_to_id('Droid'),'UNAFFILIATED'),
    ('Biggs Darklighter',183,84,'BLACK','LIGHT','BROWN',-24,'MALE', public.planet_name_to_id('Tatooine'), public.species_name_to_id('Human'),'REBEL_ALLIANCE'),
    ('Obi-Wan Kenobi',182,77,'RED','FAIR','BLUE_GRAY',-57,'MALE', public.planet_name_to_id('Stewjon'), public.species_name_to_id('Human'),'JEDI_ORDER'),
    ('Anakin Skywalker',188,84,'BLOND','FAIR','BLUE',-41.9,'MALE', public.planet_name_to_id('Tatooine'), public.species_name_to_id('Human'),'JEDI_ORDER'),
    ('Wilhuff Tarkin',180,0,'RED','FAIR','BLUE',-64,'MALE', public.planet_name_to_id('Eriadu'), public.species_name_to_id('Human'),'GALACTIC_EMPIRE'),
    ('Chewbacca',228,112,'BROWN','BROWN','BLUE',-200,'MALE', public.planet_name_to_id('Kashyyyk'), public.species_name_to_id('Wookiee'),'REBEL_ALLIANCE'),
    ('Han Solo',180,80,'BROWN','FAIR','BROWN',-29,'MALE', public.planet_name_to_id('Corellia'), public.species_name_to_id('Human'),'REBEL_ALLIANCE'),
    ('Greedo',173,74,'NONE','GREEN','BLACK',-44,'MALE', public.planet_name_to_id('Rodia'), public.species_name_to_id('Rodian'),'TRADE_FEDERATION'),
    ('Jabba Desilijic Tiure',175,1358,'NONE','GREEN','ORANGE',-600,'HERMAPHRODITE', public.planet_name_to_id('Nal Hutta'), public.species_name_to_id('Hutt'),'GALACTIC_EMPIRE'),
    ('Wedge Antilles',170,77,'BROWN','FAIR','HAZEL',-21,'MALE', public.planet_name_to_id('Corellia'), public.species_name_to_id('Human'),'REBEL_ALLIANCE'),
    ('Jek Tono Porkins',180,110,'BROWN','FAIR','BLUE',0,'MALE', public.planet_name_to_id('Bestine IV'), public.species_name_to_id('Human'),'REBEL_ALLIANCE'),
    ('Yoda',66,17,'WHITE','GREEN','BROWN',-896,'MALE', public.planet_name_to_id('Unknown'), public.species_name_to_id('Yoda''s species'),'JEDI_ORDER'),
    ('Palpatine',170,75,'GREY','PALE','YELLOW',-82,'MALE', public.planet_name_to_id('Naboo'), public.species_name_to_id('Human'),'GALACTIC_REPUBLIC'),
    ('Boba Fett',183,78.2,'BLACK','FAIR','BROWN',-31.5,'MALE', public.planet_name_to_id('Kamino'), public.species_name_to_id('Human'),'GALACTIC_EMPIRE'),
    ('IG-88',200,140,'NONE','METAL','RED',-15,'NA', public.planet_name_to_id('Unknown'), public.species_name_to_id('Droid'),'BOUNTY_HUNTERS'),
    ('Bossk',190,113,'NONE','GREEN','RED',-53,'MALE', public.planet_name_to_id('Trandosha'), public.species_name_to_id('Trandoshan'),'BOUNTY_HUNTERS'),
    ('Lando Calrissian',177,79,'BLACK','DARK','BROWN',-31,'MALE', public.planet_name_to_id('Socorro'), public.species_name_to_id('Human'),'REBEL_ALLIANCE'),
    ('Lobot',175,79,'NONE','LIGHT','BLUE',-37,'MALE', public.planet_name_to_id('Bespin'), public.species_name_to_id('Human'),'GALACTIC_EMPIRE'),
    ('Ackbar',180,83,'NONE','BROWN','ORANGE',-41,'MALE', public.planet_name_to_id('Mon Cala'), public.species_name_to_id('Mon Calamari'),'GALACTIC_REPUBLIC'),
    ('Mon Mothma',150,0,'RED','FAIR','BLUE',-48,'FEMALE', public.planet_name_to_id('Chandrila'), public.species_name_to_id('Human'),'GALACTIC_REPUBLIC'),
    ('Arvel Crynyd',0,0,'BROWN','FAIR','BROWN',0,'MALE', public.planet_name_to_id('Unknown'), public.species_name_to_id('Human'),'REBEL_ALLIANCE'),
    ('Wicket Systri Warrick',88,20,'BROWN','BROWN','BROWN',-8,'MALE', public.planet_name_to_id('Endor'), public.species_name_to_id('Ewok'),'REBEL_ALLIANCE'),
    ('Nien Nunb',160,68,'NONE','GREY','BLACK',0,'MALE', public.planet_name_to_id('Sullust'), public.species_name_to_id('Sullustan'),'REBEL_ALLIANCE'),
    ('Qui-Gon Jinn',193,89,'BROWN','FAIR','BLUE',-92,'MALE', public.planet_name_to_id('Coruscant'), public.species_name_to_id('Human'),'JEDI_ORDER'),
    ('Nute Gunray',191,90,'NONE','GREEN','RED',0,'MALE', public.planet_name_to_id('Cato Neimoidia'), public.species_name_to_id('Neimoidian'),'GALACTIC_REPUBLIC'),
    ('Finis Valorum',170,0,'BLOND','FAIR','BLUE',-91,'MALE', public.planet_name_to_id('Coruscant'), public.species_name_to_id('Human'),'GALACTIC_REPUBLIC'),
    ('Jar Jar Binks',196,66,'NONE','ORANGE','ORANGE',-52,'MALE', public.planet_name_to_id('Naboo'), public.species_name_to_id('Gungan'),'GALACTIC_REPUBLIC'),
    ('Roos Tarpals',224,82,'NONE','GREY','ORANGE',0,'MALE', public.planet_name_to_id('Naboo'), public.species_name_to_id('Gungan'),'GALACTIC_REPUBLIC'),
    ('Rugor Nass',206,0,'NONE','GREEN','ORANGE',0,'MALE', public.planet_name_to_id('Naboo'), public.species_name_to_id('Gungan'),'GALACTIC_REPUBLIC'),
    ('Ric Olié',183,0,'BROWN','FAIR','BLUE',0,'MALE', public.planet_name_to_id('Naboo'), public.species_name_to_id('Human'),'GALACTIC_REPUBLIC'),
    ('Watto',137,0,'BLACK','BLUE','YELLOW',0,'MALE', public.planet_name_to_id('Toydaria'), public.species_name_to_id('Toydarian'),'CRIMINALS'),
    ('Sebulba',112,40,'NONE','GREY','ORANGE',0,'MALE', public.planet_name_to_id('Malastare'), public.species_name_to_id('Dug'),'UNAFFILIATED'),
    ('Quarsh Panaka',183,0,'BLACK','DARK','BROWN',-62,'MALE', public.planet_name_to_id('Naboo'), public.species_name_to_id('Human'),'GALACTIC_EMPIRE'),
    ('Shmi Skywalker',163,0,'BLACK','FAIR','BROWN',-72,'FEMALE', public.planet_name_to_id('Tatooine'), public.species_name_to_id('Human'),'UNAFFILIATED'),
    ('Darth Maul',175,80,'NONE','RED','YELLOW',-54,'MALE', public.planet_name_to_id('Dathomir'), public.species_name_to_id('Zabrak'),'SITH_ORDER'),
    ('Bib Fortuna',180,0,'NONE','PALE','PINK',0,'MALE', public.planet_name_to_id('Ryloth'), public.species_name_to_id('Twi''lek'),'CRIMINALS'),
    ('Ayla Secura',178,55,'NONE','BLUE','HAZEL',-48,'FEMALE', public.planet_name_to_id('Ryloth'), public.species_name_to_id('Twi''lek'),'GALACTIC_REPUBLIC'),
    ('Dud Bolt',94,45,'NONE','BLUE','YELLOW',0,'MALE', public.planet_name_to_id('Vulpter'), public.species_name_to_id('Vulptereen'),'UNAFFILIATED'),
    ('Gasgano',122,0,'NONE','WHITE','BLACK',0,'MALE', public.planet_name_to_id('Troiken'), public.species_name_to_id('Xexto'),'UNAFFILIATED'),
    ('Ben Quadinaros',163,65,'NONE','GREY','ORANGE',0,'MALE', public.planet_name_to_id('Tund'), public.species_name_to_id('Toong'),'UNAFFILIATED'),
    ('Mace Windu',188,84,'NONE','DARK','BROWN',-72,'MALE', public.planet_name_to_id('Haruun Kal'), public.species_name_to_id('Human'),'JEDI_ORDER'),
    ('Ki-Adi-Mundi',198,82,'WHITE','PALE','YELLOW',-92,'MALE', public.planet_name_to_id('Cerea'), public.species_name_to_id('Cerean'),'JEDI_ORDER'),
    ('Kit Fisto',196,87,'NONE','GREEN','BLACK',0,'MALE', public.planet_name_to_id('Glee Anselm'), public.species_name_to_id('Nautolan'),'JEDI_ORDER'),
    ('Eeth Koth',171,0,'BLACK','BROWN','BROWN',0,'MALE', public.planet_name_to_id('Iridonia'), public.species_name_to_id('Zabrak'),'JEDI_ORDER'),
    ('Adi Gallia',184,50,'NONE','DARK','BLUE',0,'FEMALE', public.planet_name_to_id('Coruscant'), public.species_name_to_id('Tholothian'),'JEDI_ORDER'),
    ('Saesee Tiin',188,0,'NONE','PALE','ORANGE',0,'MALE', public.planet_name_to_id('Iktotch'), public.species_name_to_id('Iktotchi'),'JEDI_ORDER'),
    ('Yarael Poof',264,0,'NONE','WHITE','YELLOW',0,'MALE', public.planet_name_to_id('Quermia'), public.species_name_to_id('Quermian'),'JEDI_ORDER'),
    ('Plo Koon',188,80,'NONE','ORANGE','BLACK',-22,'MALE', public.planet_name_to_id('Dorin'), public.species_name_to_id('Kel Dor'),'JEDI_ORDER'),
    ('Mas Amedda',196,0,'NONE','BLUE','BLUE',0,'MALE', public.planet_name_to_id('Champala'), public.species_name_to_id('Chagrian'),'GALACTIC_REPUBLIC'),
    ('Gregar Typho',185,85,'BLACK','DARK','BROWN',0,'MALE', public.planet_name_to_id('Naboo'), public.species_name_to_id('Human'),'GALACTIC_REPUBLIC'),
    ('Cordé',157,0,'BROWN','LIGHT','BROWN',0,'FEMALE', public.planet_name_to_id('Naboo'), public.species_name_to_id('Human'),'GALACTIC_REPUBLIC'),
    ('Cliegg Lars',183,0,'BROWN','FAIR','BLUE',-82,'MALE', public.planet_name_to_id('Tatooine'), public.species_name_to_id('Human'),'UNAFFILIATED'),
    ('Poggle the Lesser',183,80,'NONE','GREEN','YELLOW',0,'MALE', public.planet_name_to_id('Geonosis'), public.species_name_to_id('Geonosian'),'CONFEDERACY_OF_INDEPENDENT_SYSTEMS'),
    ('Luminara Unduli',170,56.2,'BLACK','YELLOW','BLUE',-58,'FEMALE', public.planet_name_to_id('Mirial'), public.species_name_to_id('Mirialan'),'GALACTIC_REPUBLIC'),
    ('Barriss Offee',166,50,'BLACK','YELLOW','BLUE',-40,'FEMALE', public.planet_name_to_id('Mirial'), public.species_name_to_id('Mirialan'),'JEDI_ORDER'),
    ('Dormé',165,0,'BROWN','LIGHT','BROWN',0,'FEMALE', public.planet_name_to_id('Naboo'), public.species_name_to_id('Human'),'GALACTIC_REPUBLIC'),
    ('Dooku',193,80,'WHITE','FAIR','BROWN',-102,'MALE', public.planet_name_to_id('Serenno'), public.species_name_to_id('Human'),'SITH_ORDER'),
    ('Bail Prestor Organa',191,0,'BLACK','TAN','BROWN',-67,'MALE', public.planet_name_to_id('Alderaan'), public.species_name_to_id('Human'),'REBEL_ALLIANCE'),
    ('Jango Fett',183,79,'BLACK','TAN','BROWN',-66,'MALE', public.planet_name_to_id('Concord Dawn'), public.species_name_to_id('Human'),'GALACTIC_REPUBLIC'),
    ('Zam Wesell',168,55,'BLOND','FAIR','YELLOW',0,'FEMALE', public.planet_name_to_id('Zolan'), public.species_name_to_id('Clawdite'),'BOUNTY_HUNTERS'),
    ('Dexter Jettster',198,102,'NONE','BROWN','YELLOW',0,'MALE', public.planet_name_to_id('Ojom'), public.species_name_to_id('Besalisk'),'GALACTIC_REPUBLIC'),
    ('Lama Su',229,88,'NONE','GREY','BLACK',0,'MALE', public.planet_name_to_id('Kamino'), public.species_name_to_id('Kaminoan'),'JEDI_ORDER'),
    ('Taun We',213,0,'NONE','GREY','BLACK',0,'FEMALE', public.planet_name_to_id('Kamino'), public.species_name_to_id('Kaminoan'),'GALACTIC_EMPIRE'),
    ('Jocasta Nu',167,0,'WHITE','FAIR','BLUE',0,'FEMALE', public.planet_name_to_id('Coruscant'), public.species_name_to_id('Human'),'JEDI_ORDER'),
    ('Ratts Tyerell',79,15,'NONE','GREY','BLUE',0,'MALE', public.planet_name_to_id('Aleen Minor'), public.species_name_to_id('Aleena'),'UNAFFILIATED'),
    ('R4-P17',96,0,'NONE','SILVER','RED',0,'FEMALE', public.planet_name_to_id('Unknown'), public.species_name_to_id('Droid'),'JEDI_ORDER'),
    ('Wat Tambor',193,48,'NONE','GREEN','BLACK',0,'MALE', public.planet_name_to_id('Skako'), public.species_name_to_id('Skakoan'),'CONFEDERACY_OF_INDEPENDENT_SYSTEMS'),
    ('San Hill',191,0,'NONE','GREY','GOLD',0,'MALE', public.planet_name_to_id('Muunilinst'), public.species_name_to_id('Muun'),'CONFEDERACY_OF_INDEPENDENT_SYSTEMS'),
    ('Shaak Ti',178,57,'NONE','RED','BLACK',0,'FEMALE', public.planet_name_to_id('Shili'), public.species_name_to_id('Togruta'),'JEDI_ORDER'),
    ('Grievous',216,159,'NONE','BROWN','GREEN',0,'MALE', public.planet_name_to_id('Kalee'), public.species_name_to_id('Kaleesh'),'CONFEDERACY_OF_INDEPENDENT_SYSTEMS'),
    ('Tarfful',234,136,'BROWN','BROWN','BLUE',0,'MALE', public.planet_name_to_id('Kashyyyk'), public.species_name_to_id('Wookiee'),'GALACTIC_REPUBLIC'),
    ('Raymus Antilles',188,79,'BROWN','LIGHT','BROWN',0,'MALE', public.planet_name_to_id('Alderaan'), public.species_name_to_id('Human'),'REBEL_ALLIANCE'),
    ('Tion Medon',206,80,'NONE','GREY','BLACK',0,'MALE', public.planet_name_to_id('Utapau'), public.species_name_to_id('Pau''an'),'GALACTIC_REPUBLIC'),
    ('Finn',0,0,'BLACK','DARK','DARK',0,'MALE', public.planet_name_to_id('Unknown'), public.species_name_to_id('Human'),'RESISTANCE'),
    ('Rey',0,0,'BROWN','LIGHT','HAZEL',0,'FEMALE', public.planet_name_to_id('Jakku'), public.species_name_to_id('Human'),'RESISTANCE'),
    ('Poe Dameron',0,0,'BROWN','LIGHT','BROWN',0,'MALE', public.planet_name_to_id('Yavin IV'), public.species_name_to_id('Human'),'GALACTIC_REPUBLIC'),
    ('BB8',0,0,'NONE','NONE','BLACK',0,'NA', public.planet_name_to_id('Unknown'), public.species_name_to_id('Droid'),'RESISTANCE'),
    ('Captain Phasma',0,0,'NONE','WHITE','BLUE',0,'FEMALE', public.planet_name_to_id('Unknown'), public.species_name_to_id('Human'),'FIRST_ORDER'),
    ('Padmé Amidala',165,45,'BROWN','LIGHT','BROWN',-46,'FEMALE', public.planet_name_to_id('Naboo'), public.species_name_to_id('Human'),'GALACTIC_REPUBLIC');
